### ISSUE TITLE
V2 Bugs

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#468]
A list of bugs and improvements

## Dashboard
- [x] Properly hide pools with negative yield.
- [ ] ~Add hidden flag to DashbordRow~
- [x] Fix parent row aggregate values
- [ ] ~If no pools available remove parent~
- [ ] ~Switch Fiat/Crypto (parked -  Daniele)~ (created separate issue https://github.com/tempus-finance/tempus-app/issues/494)

## Navbar 
- [x] remove analytics link   
- [x] port community from v1   
- [x] mouse over and active link design 
- [x] settings (slippage - dark mode (disabled) -  language (disabled)) (removed settings for now).

## Sidebar
- [x] Mouse over
- [x] Check if user has LP tokens, if not then Remove liquidity option needs to be hidden/disabled

## Operations

TokenSelector
- [x] fixed width
- [ ] ~disable state~ (Created separate issue: https://github.com/tempus-finance/tempus-app/issues/495)

CurrencyInput
- [x] Disabled state
- [x] Fix when long number to 8 digit precision
- [x] Max button disabled if input is disabled
- [ ] ~Currency input changes should be debounced 200-500ms or user tabs out~ (Created separate issue - #496)

Approve / Execute
- [x] Add state (disabled - pending - mouse over)

Pool
- [x] Fees needs (i) icon

Term
- [ ] ~Time remaining in days~ (tried it, there is not enough space for (years x, months y, days z) string.

Deposit
- [x] Fixed yield at maturity values
- [x] Total available at maturity
  
Withdraw 
- [x] Once done, go back to Deposit 
- [x] Withdraw link hidden or disabled?

Mint 
- [x] Doesn't work?

Swap
- [x] Swap link hidden or disabled?

Early Redeem
- [x] Balance is 0?

Current position 
- [x]  order principals, staked principals, staked yields, yields
- [ ]   ~add pattern to staked~ (Created separate issue for this one https://github.com/tempus-finance/tempus-app/issues/497)

Pool
- [x]    Rename Market implied yield to Future APR
- [ ]    ~add tooltip to future apr~ (Created separate issue: https://github.com/tempus-finance/tempus-app/issues/498)
- [ ]    ~indicators showing after 14 days have passed, all rows need indicator (hidden for now - add them in next 14 days)~ (Created separate issue for this https://github.com/tempus-finance/tempus-app/issues/499)

Profit loss 
- [x] never starts with minimum zero

Fonts
- [x] change wallet fonts to be consistent with Navbar
- [x] change Filter fonts to be consistent with rows
- [x] default font is `Source Sans Pro`

Images
- [x] Old logo
- [x] Old favicon

**Comment by lazarmitic** [comment]
Separate issues created for remaining tasks. Closing this one.
